[package]
name = "arrowcss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
config = "0.13.4"
cssparser = "0.33.0"
lazy_static = "1.4.0"
lightningcss = { version = "1.0.0-alpha.55", features = ["into_owned"] }
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
regex = "1.10.2"
serde = "1.0.193"
serde_json = "1.0.108"
smallvec = { version = "1.11.2", features = ["const_generics"] }
arrowcss_css_macro = { version = "0.1.0", path = "../arrowcss_css_macro" }
fxhash = "0.2.1"
rayon = "1.10.0"
walkdir = "2.5.0"
either = "1.10.0"
enum_dispatch = "0.3.13"
clap = { version = "4.5.4", features = ["derive"] }
phf = { version = "0.11.2", features = ["macros"] }
colored = "2.1.0"
cssparser-macros = "0.6.1"

[lib]
bench = false
