[workspace]
members = [
  "bindings/core_node",
  "bindings/core_wasm",
  "crates/arrowcss",
  "crates/arrowcss_css_macro",
  "crates/arrowcss_extractor",
  "crates/arrowcss_cli",
]
resolver = "2"
[profile.release]
lto = true
codegen-units = 1

[profile.bench]
debug = true

[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
