[workspace]
members = [
  "bindings/binding_core_node",
  "crates/arrowcss",
]
resolver = "2"
[profile.release]
# lto = true

# debug = true
# opt-level = 'z'

[profile.bench]
debug = true
# lto = true

# Optimize for iteration
[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3