[package]
name    = "rswind_common"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]

[dependencies]
rayon   = { workspace = true }
either  = { workspace = true }
smol_str = { workspace = true }
