[package]
edition = "2021"
name = "binding_core_wasm"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
arrowcss = { path = "../../crates/arrowcss" }
# wasm-bindgen-rayon = "1.2.1"
console_error_panic_hook = "0.1.7"
lazy_static = "1.4.0"
